// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvBIvg-NbFkAJZJXYzsNaM3nxlOFwIwE',
    appId: '1:887549009134:web:f91910136fc29ee236a7ff',
    messagingSenderId: '887549009134',
    projectId: 'real-estate-1258f',
    authDomain: 'real-estate-1258f.firebaseapp.com',
    storageBucket: 'real-estate-1258f.firebasestorage.app',
    measurementId: 'G-E490Y82Q53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn2sh2lEp1SAZkGudeOVWrNZgBjwxfKHQ',
    appId: '1:887549009134:android:6e01d16d38fb488936a7ff',
    messagingSenderId: '887549009134',
    projectId: 'real-estate-1258f',
    storageBucket: 'real-estate-1258f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9uvjwnu5S98z3IMf7xT0NVpWE5SlTeGk',
    appId: '1:887549009134:ios:8b7bb1b02e081bf436a7ff',
    messagingSenderId: '887549009134',
    projectId: 'real-estate-1258f',
    storageBucket: 'real-estate-1258f.firebasestorage.app',
    iosClientId: '887549009134-rivv3jfcb9jui801jvo4cut2fbu469cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.realesate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9uvjwnu5S98z3IMf7xT0NVpWE5SlTeGk',
    appId: '1:887549009134:ios:8b7bb1b02e081bf436a7ff',
    messagingSenderId: '887549009134',
    projectId: 'real-estate-1258f',
    storageBucket: 'real-estate-1258f.firebasestorage.app',
    iosClientId: '887549009134-rivv3jfcb9jui801jvo4cut2fbu469cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.realesate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjvBIvg-NbFkAJZJXYzsNaM3nxlOFwIwE',
    appId: '1:887549009134:web:9c28624bc2561ee836a7ff',
    messagingSenderId: '887549009134',
    projectId: 'real-estate-1258f',
    authDomain: 'real-estate-1258f.firebaseapp.com',
    storageBucket: 'real-estate-1258f.firebasestorage.app',
    measurementId: 'G-5WY5FL5M4C',
  );
}
